/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FunilPageRouteImport } from './routes/funil.$page'
import { Route as FunilPosSplatRouteImport } from './routes/funil.pos.$'
import { Route as ApiPixStatusRouteImport } from './routes/api/pix/status'
import { Route as ApiPixCreateRouteImport } from './routes/api/pix/create'
import { Route as ApiCpfCpfRouteImport } from './routes/api/cpf/$cpf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilPageRoute = FunilPageRouteImport.update({
  id: '/funil/$page',
  path: '/funil/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilPosSplatRoute = FunilPosSplatRouteImport.update({
  id: '/funil/pos/$',
  path: '/funil/pos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixStatusRoute = ApiPixStatusRouteImport.update({
  id: '/api/pix/status',
  path: '/api/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixCreateRoute = ApiPixCreateRouteImport.update({
  id: '/api/pix/create',
  path: '/api/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCpfCpfRoute = ApiCpfCpfRouteImport.update({
  id: '/api/cpf/$cpf',
  path: '/api/cpf/$cpf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funil/$page': typeof FunilPageRoute
  '/api/cpf/$cpf': typeof ApiCpfCpfRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/funil/pos/$': typeof FunilPosSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funil/$page': typeof FunilPageRoute
  '/api/cpf/$cpf': typeof ApiCpfCpfRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/funil/pos/$': typeof FunilPosSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funil/$page': typeof FunilPageRoute
  '/api/cpf/$cpf': typeof ApiCpfCpfRoute
  '/api/pix/create': typeof ApiPixCreateRoute
  '/api/pix/status': typeof ApiPixStatusRoute
  '/funil/pos/$': typeof FunilPosSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/funil/$page'
    | '/api/cpf/$cpf'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/funil/pos/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/funil/$page'
    | '/api/cpf/$cpf'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/funil/pos/$'
  id:
    | '__root__'
    | '/'
    | '/funil/$page'
    | '/api/cpf/$cpf'
    | '/api/pix/create'
    | '/api/pix/status'
    | '/funil/pos/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FunilPageRoute: typeof FunilPageRoute
  ApiCpfCpfRoute: typeof ApiCpfCpfRoute
  ApiPixCreateRoute: typeof ApiPixCreateRoute
  ApiPixStatusRoute: typeof ApiPixStatusRoute
  FunilPosSplatRoute: typeof FunilPosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil/$page': {
      id: '/funil/$page'
      path: '/funil/$page'
      fullPath: '/funil/$page'
      preLoaderRoute: typeof FunilPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil/pos/$': {
      id: '/funil/pos/$'
      path: '/funil/pos/$'
      fullPath: '/funil/pos/$'
      preLoaderRoute: typeof FunilPosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix/status': {
      id: '/api/pix/status'
      path: '/api/pix/status'
      fullPath: '/api/pix/status'
      preLoaderRoute: typeof ApiPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pix/create': {
      id: '/api/pix/create'
      path: '/api/pix/create'
      fullPath: '/api/pix/create'
      preLoaderRoute: typeof ApiPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cpf/$cpf': {
      id: '/api/cpf/$cpf'
      path: '/api/cpf/$cpf'
      fullPath: '/api/cpf/$cpf'
      preLoaderRoute: typeof ApiCpfCpfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FunilPageRoute: FunilPageRoute,
  ApiCpfCpfRoute: ApiCpfCpfRoute,
  ApiPixCreateRoute: ApiPixCreateRoute,
  ApiPixStatusRoute: ApiPixStatusRoute,
  FunilPosSplatRoute: FunilPosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
